

# **02_Taller_Python**

## Índice

- <a href='#t8'>8. PANDAS</a>
     - <a href='#8.1.'>8.1. Crear DataFrames</a>
     - <a href='#8.2.'>8.2. Importar bases de datos</a>
     - <a href='#8.3.'>8.3. Modificar columnas</a>
     - <a href='#8.4.'>8.4. Concatenaciones y merge</a>
     - <a href='#8.5.'>8.5. Exportar DataFrames</a>
- <a href='#t9'>9. NUMPY</a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##  <a id='t8'>8. PANDAS (Python Data Analysis)</a>

Un DataFrame en Pandas es una estructura de datos tabular bidimensional que se utiliza para almacenar y manipular datos en Python. Es similar a una hoja de cálculo o una tabla de base de datos, donde los datos se organizan en filas y columnas. Cada columna puede contener datos de diferentes tipos (números, texto, fechas, etc.).

### 8.1. <a id='8.1.'>Crear Pandas DataFrames</a>

A partir de una lista de listas

In [ ]:
import pandas as pd

In [ ]:
columnas = ['Departamento', 'Provincia']
fila_1   = ['Amazonas', 'Chachapoyas']
fila_2   = ['Cajamarca',  'Chota']

data_1 = [fila_1, fila_2]

ejemplo_1 = pd.DataFrame( data = data_1, columns = columnas )
ejemplo_1

  Departamento    Provincia
0     Amazonas  Chachapoyas
1    Cajamarca        Chota

Desde un diccionario

In [ ]:
data_2 = {
            'Nombre': ['Juan', 'María', 'Luis'],
            'Edad': [25, 30, 28]
        }

ejemplo_2 = pd.DataFrame(data_2)
ejemplo_2

  Nombre  Edad
0   Juan    25
1  María    30
2   Luis    28

### 8.2. <a id='8.2.'>Importar bases de datos</a>

| Método                                | Descripción                                                      |
|---------------------------------------|------------------------------------------------------------------|
| `pd.read_csv('archivo.csv')`          | Importa datos desde un archivo CSV.                              |
| `pd.read_excel('archivo.xlsx')`       | Importa datos desde un archivo Excel.                            |
| `pd.read_stata('srchivo.dta')`        | Importa datos desde un archivo Stata                             |
| `pd.read_json('archivo.json')`        | Importa datos desde un archivo JSON.                             |
| `pd.read_html('URL o archivo.html')`  | Importa datos desde una página web o archivo HTML.               |

Importar desde un archivo csv

In [ ]:
url_1 = 'https://raw.githubusercontent.com/darlaabril/Taller-Python/main/DataPanda%20-%20Hoja%201%20(1).csv'
df_1  = pd.read_csv(url_1)
df_1

     Departamento           Capital  Pob2007  Pob2017  CodDepartamento
0        Amazonas       Chachapoyas   375993   379384                1
1          Áncash            Huaraz  1063459  1083519                2
2        Apurímac           Abancay   404190   405759                3
3        Arequipa          Arequipa  1152303  1382730                4
4        Ayacucho          Ayacucho   612489   616176                5
5       Cajamarca         Cajamarca  1387809  1341012                6
6          Callao            Callao   876877   994494                7
7           Cusco             Cuzco  1171403  1205527                8
8    Huancavelica      Huancavelica   454797   347639                9
9         Huánuco           Huánuco   762223   721047               10
10            Ica               Ica   711932   850765               11
11          Junín          Huancayo  1225474  1246038               12
12    La Libertad          Trujillo  1617050  1778080               13
13     Lambayeque          Chiclayo  1112868  1197260               14
14           Lima              Lima  8445211  9485405               15
15         Loreto           Iquitos   891732   883510               16
16  Madre de Dios  Puerto Maldonado   109555   141070               17
17       Moquegua          Moquegua   161533   174863               18
18          Pasco    Cerro de Pasco   280449   254065               19
19          Piura             Piura  1676315  1856809               20
20           Puno              Puno  1268441  1172697               21
21     San Martín         Moyobamba   728808   813381               22
22          Tacna             Tacna   288781   329332               23
23         Tumbes            Tumbes   200306   224863               24
24        Ucayali          Pucallpa   432159   496459               25

Importar desde un archivo stata

In [ ]:
url_2 = 'iris.dta'
df_2  = pd.read_stata( url_2 )
df_2

FileNotFoundError: [Errno 2] No such file or directory: 'iris.dta'

### 8.3. <a id='8.3.'>Modificar Pandas DataFrames</a>

| Método                                                 | Nombre                      | Descripción                                                     
|--------------------------------------------------------|-----------------------------|------------------------------------------------------------------|
|`df[nueva_columna] = valor`                             | Asignación directa          | Permite asignar nuevos valores o cambiar valores existentes directamente a través de la etiqueta de columna y fila.                              |                       |
|`loc` e `iloc`                                          | Indexación                  | Permite acceder o asignar datos usando etiquetas (loc) e índices (iloc)                              |
|`df.drop(columna_a_eliminar, axis = 1)`                 | Eliminar filas o columnas   | Permite elimiar una o más columnas                             |
|`df.rename(columns={'nombre_anterior': 'nuevo_nombre'})`| Renombrar filas o columnas  | Permite renombrar una o más columnas.               |

### Asignación directa

In [ ]:
df_2[ 'place' ] = 'Italia'
df_2

NameError: name 'df_2' is not defined

In [ ]:
df_2[ 'doubled_petal_width' ] = df_2[ 'petal_width' ]*2
df_2

,index,sepal_length,sepal_width,petal_length,petal_width,variety,place,doubled_petal_width
0,0,5.1,3.5,1.4,0.2,Setosa,Italia,0.4
1,1,4.9,3.0,1.4,0.2,Setosa,Italia,0.4
2,2,4.7,3.2,1.3,0.2,Setosa,Italia,0.4
3,3,4.6,3.1,1.5,0.2,Setosa,Italia,0.4
4,4,5.0,3.6,1.4,0.2,Setosa,Italia,0.4
...,...,...,...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3,Virginica,Italia,4.6
146,146,6.3,2.5,5.0,1.9,Virginica,Italia,3.8
147,147,6.5,3.0,5.2,2.0,Virginica,Italia,4.0
148,148,6.2,3.4,5.4,2.3,Virginica,Italia,4.6
149,149,5.9,3.0,5.1,1.8,Virginica,Italia,3.6

### Indexación

In [ ]:
df_2.loc[df_2['variety'] == 'Setosa', 'place'] = 'España'
df_2

,index,sepal_length,sepal_width,petal_length,petal_width,variety,place,doubled_petal_width
0,0,5.1,3.5,1.4,0.2,Setosa,España,0.4
1,1,4.9,3.0,1.4,0.2,Setosa,España,0.4
2,2,4.7,3.2,1.3,0.2,Setosa,España,0.4
3,3,4.6,3.1,1.5,0.2,Setosa,España,0.4
4,4,5.0,3.6,1.4,0.2,Setosa,España,0.4
...,...,...,...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3,Virginica,Italia,4.6
146,146,6.3,2.5,5.0,1.9,Virginica,Italia,3.8
147,147,6.5,3.0,5.2,2.0,Virginica,Italia,4.0
148,148,6.2,3.4,5.4,2.3,Virginica,Italia,4.6
149,149,5.9,3.0,5.1,1.8,Virginica,Italia,3.6

In [ ]:
df_2.loc[0, 'variety'] = 'Versicolor'
df_2

,index,sepal_length,sepal_width,petal_length,petal_width,variety,place,doubled_petal_width
0,0,5.1,3.5,1.4,0.2,Versicolor,España,0.4
1,1,4.9,3.0,1.4,0.2,Setosa,España,0.4
2,2,4.7,3.2,1.3,0.2,Setosa,España,0.4
3,3,4.6,3.1,1.5,0.2,Setosa,España,0.4
4,4,5.0,3.6,1.4,0.2,Setosa,España,0.4
...,...,...,...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3,Virginica,Italia,4.6
146,146,6.3,2.5,5.0,1.9,Virginica,Italia,3.8
147,147,6.5,3.0,5.2,2.0,Virginica,Italia,4.0
148,148,6.2,3.4,5.4,2.3,Virginica,Italia,4.6
149,149,5.9,3.0,5.1,1.8,Virginica,Italia,3.6

In [ ]:
df_2.iloc[0, 6] = 'Malta'
df_2

,index,sepal_length,sepal_width,petal_length,petal_width,variety,place,doubled_petal_width
0,0,5.1,3.5,1.4,0.2,Versicolor,Malta,0.4
1,1,4.9,3.0,1.4,0.2,Setosa,España,0.4
2,2,4.7,3.2,1.3,0.2,Setosa,España,0.4
3,3,4.6,3.1,1.5,0.2,Setosa,España,0.4
4,4,5.0,3.6,1.4,0.2,Setosa,España,0.4
...,...,...,...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3,Virginica,Italia,4.6
146,146,6.3,2.5,5.0,1.9,Virginica,Italia,3.8
147,147,6.5,3.0,5.2,2.0,Virginica,Italia,4.0
148,148,6.2,3.4,5.4,2.3,Virginica,Italia,4.6
149,149,5.9,3.0,5.1,1.8,Virginica,Italia,3.6

### Eliminar filas o columnas

In [ ]:
df_2 = df_2.drop('doubled_petal_width', axis = 1)
df_2

,index,sepal_length,sepal_width,petal_length,petal_width,variety,place
0,0,5.1,3.5,1.4,0.2,Versicolor,Malta
1,1,4.9,3.0,1.4,0.2,Setosa,España
2,2,4.7,3.2,1.3,0.2,Setosa,España
3,3,4.6,3.1,1.5,0.2,Setosa,España
4,4,5.0,3.6,1.4,0.2,Setosa,España
...,...,...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3,Virginica,Italia
146,146,6.3,2.5,5.0,1.9,Virginica,Italia
147,147,6.5,3.0,5.2,2.0,Virginica,Italia
148,148,6.2,3.4,5.4,2.3,Virginica,Italia
149,149,5.9,3.0,5.1,1.8,Virginica,Italia

In [ ]:
df_2 = df_2.drop(0, axis = 0)
df_2

,index,sepal_length,sepal_width,petal_length,petal_width,variety,place
1,1,4.9,3.0,1.4,0.2,Setosa,España
2,2,4.7,3.2,1.3,0.2,Setosa,España
3,3,4.6,3.1,1.5,0.2,Setosa,España
4,4,5.0,3.6,1.4,0.2,Setosa,España
5,5,5.4,3.9,1.7,0.4,Setosa,España
...,...,...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3,Virginica,Italia
146,146,6.3,2.5,5.0,1.9,Virginica,Italia
147,147,6.5,3.0,5.2,2.0,Virginica,Italia
148,148,6.2,3.4,5.4,2.3,Virginica,Italia
149,149,5.9,3.0,5.1,1.8,Virginica,Italia

### Renombrar columnas

In [ ]:
df_2 = df_2.rename(columns = {'place': 'country'})
df_2

,index,sepal_length,sepal_width,petal_length,petal_width,variety,country
1,1,4.9,3.0,1.4,0.2,Setosa,España
2,2,4.7,3.2,1.3,0.2,Setosa,España
3,3,4.6,3.1,1.5,0.2,Setosa,España
4,4,5.0,3.6,1.4,0.2,Setosa,España
5,5,5.4,3.9,1.7,0.4,Setosa,España
...,...,...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3,Virginica,Italia
146,146,6.3,2.5,5.0,1.9,Virginica,Italia
147,147,6.5,3.0,5.2,2.0,Virginica,Italia
148,148,6.2,3.4,5.4,2.3,Virginica,Italia
149,149,5.9,3.0,5.1,1.8,Virginica,Italia

### 8.4. <a id='8.4.'>Concatenaciones y merge</a>

| Método                                | Descripción                                                      |
|---------------------------------------|------------------------------------------------------------------|
| Concatenaciones          | Combina DataFrames apilando filas (vertical) o pegando columnas (horizontal) uno debajo del otro o al lado. Útil cuando se cuenta con DataFrames con la misma estructura y se desea unirlos sin considerar valores coincidentes.                              |
| Merge                    | Combina DataFrames en función de una o más columnas comunes. Útil cuando se desea combinar datos en función de valores coincidentes en columnas específicas.                            |

#### Concatenación vertical

In [ ]:
data_3 = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df_3 = pd.DataFrame(data_3)

data_4 = {'A': [7, 8], 'B': [9, 10]}
df_4 = pd.DataFrame(data_4)

In [ ]:
df_3

   A  B
0  1  4
1  2  5
2  3  6

In [ ]:
df_4

   A   B
0  7   9
1  8  10

In [ ]:
df_concat_vertical = pd.concat([df_3, df_4], axis=0)
df_concat_vertical

   A   B
0  1   4
1  2   5
2  3   6
0  7   9
1  8  10

#### Concatenación horizontal

In [ ]:
data_5 = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df_5 = pd.DataFrame(data_5)

data_6 = {'C': [7, 8, 9], 'D': [10, 11, 12]}
df_6 = pd.DataFrame(data_6)

In [ ]:
df_5

   A  B
0  1  4
1  2  5
2  3  6

In [ ]:
df_6

   C   D
0  7  10
1  8  11
2  9  12

In [ ]:
df_concat_horizontal = pd.concat([df_5, df_6], axis=1)
df_concat_horizontal

   A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

#### Merge

In [ ]:
data_7 = {'clave': ['A', 'B', 'C'], 'valor1': [1, 2, 3]}
df_7 = pd.DataFrame(data_7)

data_8 = {'clave': ['B', 'C', 'D'], 'valor2': [4, 5, 6]}
df_8 = pd.DataFrame(data_8)

In [ ]:
df_7

  clave  valor1
0     A       1
1     B       2
2     C       3

In [ ]:
df_8

  clave  valor2
0     B       4
1     C       5
2     D       6

In [ ]:
df_merged_1 = pd.merge(df_7, df_8, on='clave', how='inner')
df_merged_1

  clave  valor1  valor2
0     B       2       4
1     C       3       5

In [ ]:
df_merged_1 = pd.merge(df_7, df_8, on='clave', how='outer')
df_merged_1

  clave  valor1  valor2
0     A     1.0     NaN
1     B     2.0     4.0
2     C     3.0     5.0
3     D     NaN     6.0

### 8.5. <a id='8.5.'>Exportar DataFrames</a>

| Método                                | Descripción                                                      |
|---------------------------------------|------------------------------------------------------------------|
| `to_csv('archivo.csv')`          | Exporta un DataFrame a un archivo CSV.                              |
| `to_excel('archivo.xlsx')`       | Exporta un DataFrame a un archivo Excel.                            |
| `to_stata('srchivo.dta')`        | Exporta un DataFrame a un archivo Stata                             |
| `to_json('archivo.json')`        | Exporta un DataFrame a un archivo JSON.                             |
| `to_html('archivo.html')`        | Exporta un DataFrame a un archivo HTML.               |

In [ ]:
df_concat_vertical.to_csv( 'df_concat_vertical.csv' )

In [ ]:
df_merged_1.to_stata( 'df_merged_1.dta' )

##  <a id='t9'>9. NUMPY (Numerical Python)</a>

#### Arrays de 1 dimension (array 1D ):

![image.png]()

Se trata de una biblioteca utilizada para realizar cálculos numéricos y científicos. Proporciona un objeto de matriz multidimensional llamado `ndarray` que es más eficiente y conveniente para operaciones matemáticas en comparación con las listas de Python estándar.

| Método                   | Descripción                                              |
|--------------------------|------------------------------------------------------------------|
| `np.array(a)`             | Crea un array np de -dimensiones a partir de la secuencia a.                            |
| `np.linspace(a, b, N)`             | Crea un array np 1D con N valores equiespaciados <br> desde a hasta b (inclusivamente). |
| `np.arange(a, b, step)`             | Crea un array np 1D con valores desde a hasta b (exclusivamente) <br> incrementados por step.                       |
| `np.zeros(N)`  | Crea un array np 1D de ceros de longitud N.                           |
| `np.zeros((n, m))`             | Crea un array np 2D de ceros con n filas y m columnas.                            |
| `np.ones(N)`             | Crea un array np 1D de unos de longitud N. |
| `np.ones((n, m))`             | Crea un array np 2D de unos con n filas y m columnas.                       |
| `np.eye(N)`  | Crea un array np 2D con n filas y m columnas <br> con unos en la diagonal (matriz identidad de tamaño N).                           |
| `np.concatenate()`             | Une una secuencia de arrays a lo largo de un eje existente.                            |
| `np.hstack()`             | Apila arrays en secuencia horizontalmente (columna por columna). |
| `np.vstack()`             | Apila arrays en secuencia verticalmente (fila por fila).                       |
| `np.column_stack()`  | Apila arrays 1-D como columnas en un array 2-D.                           |
| `np.random.normal(`             | Genera muestras aleatorias de una distribución normal (Gaussiana). |
| `np.linalg.inv()`             | Calcula el inverso (multiplicativo) de una matriz.                       |
| `np.dot()` o `@`  | Multiplicación de matrices.                           |

In [ ]:
import numpy as np

In [ ]:
x = [3, 4, 5, 1]
print(x)

[3, 4, 5, 1]

In [ ]:
miarray = np.array([3, 4, 5, 1])
print(miarray)
type(miarray)

[3 4 5 1]

numpy.ndarray

In [ ]:
milista = [3, 4, 5, 1]
print(milista)

[3, 4, 5, 1]

In [ ]:
len(miarray)

4

In [ ]:
miarray.shape

(4,)

Función  <b>arange(n)</b> se puede crear un array 1 dimensión de numeros secuenciales comenzando 0 y terminando en n (no se incluye n).

In [ ]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a= np.arange(5)
b= [0, 1, 2, 3, 4]

print(f'{a} es de la clase {type(a)}')
print(f'{b} es de la clase {type(b)}')

[0 1 2 3 4] es de la clase <class 'numpy.ndarray'>
[0, 1, 2, 3, 4] es de la clase <class 'list'>

<b>arange(inicial, final, paso)</b>

In [ ]:
np.arange(11, 1, -2)

In [ ]:
# Crear un NumPy array de 1D con 11 valores de 0 a 1 con espacios iguales
array_1 = np.linspace( 0, 1, 11 )
print(array_1)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

#### Creando arrays de 2 dimensiones

![image.png]()

In [ ]:
miarray = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
miarray

In [ ]:
miarray.shape

#### Creando arrays de 3 dimensiones

![image.png]()

Se puede crear una array 3D a partir de un array unidimensional haciendo reshape(dim_axis0, dim_axis1, dim_axis2). La dimension del array unidimensional debe ser el producto de las 3 dimensiones: dim_axis0 * dim_axis1 * dim_axis2

In [ ]:
miarray = np.array([ [[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]] , [[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]] ])
miarray

In [ ]:
miarray.shape

In [ ]:
miarray = np.arange(24)
miarray

In [ ]:
miarray.reshape(4,6)

In [ ]:
miarray = miarray.reshape(4,3,2)
miarray

In [ ]:
miarray.shape

In [ ]:
miarray.flatten()

#### Creando arrays de ceros, unos o valores constantes

In [ ]:
np.zeros((2, 3))

In [ ]:
np.ones((3, 4), dtype=int)

In [ ]:
np.full((3, 5), 13)

###  Accediendo a datos de arrays numpy

Por ejemplo, si X es un array de 2 dimensiones, entonces :
 - X[ i , : ] es la fila i del array.
 - X[ : , j ] es la columna j del array
Cuando se especifica una dimension y todas las otras dimensiones de la derecha son :, entonces es opcional colocar los simbolos : Por ejemplo
  - en un array 2D,  X[ i, : ] es lo mismo que X[ i ]  (fila i)
  - en un array 3D,  X[ i, : , : ] es lo mismo que X[ i ] (matriz i)

In [ ]:
miarray = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(miarray)

In [ ]:
miarray[1,2]

In [ ]:
miarray[2,:]

In [ ]:
miarray[2]

In [ ]:
x= miarray[:,2]
x

In [ ]:
x.shape

In [ ]:
x = miarray[-2]
x

In [ ]:
miarray[-1,-1]

### Algunos ejemplos

In [ ]:
# Crear un NumPy array de 1D con 5 ceros
array_2 = np.zeros(5)
print(array_2)

[0. 0. 0. 0. 0.]

In [ ]:
# Crear un NumPy array de 2D de 5 * 10
array_3 = np.zeros( (5, 10) )
print(array_3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

In [ ]:
# Crear una matriz de identidad de 10*10
array_4 = np.eye(10)
print(array_4)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

In [ ]:
# Concatenar NumPy Arrays

x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])

In [ ]:
x

array([1, 1, 1])

In [ ]:
y

array([2, 2, 2])

In [ ]:
z

array([3, 3, 3])

In [ ]:
vstacked = np.vstack( (x, y, z) )
print(vstacked)

[[1 1 1]
 [2 2 2]
 [3 3 3]]

In [ ]:
hstacked = np.hstack( (x,y,z) )
print(hstacked)

[1 1 1 2 2 2 3 3 3]

# <font color=blue>10. Visualizacion de datos en Python </font>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_excel('Terminos_tiempo.xlsx')
data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Terminos_tiempo.xlsx'

In [ ]:
data.tail()

In [ ]:
data.info()

In [ ]:
data.describe()

## Resaltando Máximos y Minimos con colores

In [ ]:
data.style.highlight_max(color='green').highlight_min(color='red')

funcion <b>background_gradient()</b>para pintar las celdas con un color de acuerdo a su valor. Existe varios mapas de colores disponibles (https://matplotlib.org/gallery/color/colormap_reference.html)

In [ ]:
data.style.background_gradient(subset=['data science', 'machine learning'], cmap='BuGn')

In [ ]:
data.style.background_gradient(subset=['data science'], cmap='BuGn').background_gradient(subset=['machine learning'], cmap='Greys')

## Usando barras para mostrar valores de tablas

In [ ]:
data.style.bar(color='green', subset=['data science', 'deep learning'])

In [ ]:
df_estilizado = data.style.format({'Mes':'{:%m/%Y}'}).background_gradient(subset=['data science'], cmap='BuGn').bar(color='red', subset=['deep learning']).background_gradient(subset=['machine learning'], cmap='plasma')
df_estilizado

In [ ]:
df_estilizado.to_excel('prueba.xlsx')

<a name='matplotlib'></a>
# <font color=blue>Visualizacion con Matplotlib</font>

<b>matplotlib.pyplot</b> provee una colección de funciones al estilo de comandos. Cada función de pyplot realiza algún cambio en una figura

In [ ]:
import matplotlib.pyplot as plt

## Plot de linea

In [ ]:
data = pd.read_excel('My Drive/Mi Unidad//Terminos_tiempo.xlsx')
plt.figure(figsize=(8,4))
plt.plot( data['Mes'], data['data science'] )
plt.show()

In [ ]:
plt.figure(figsize=(8,4))
plt.plot(data['Mes'], data['data science'], label='data science')
plt.title('Popularidad de Terminos Buscados por fecha')
plt.xlabel('Fecha')
plt.ylabel('Popularidad')
plt.grid(True)
plt.legend()
plt.show()

### Ploteando multiples variables

In [ ]:
plt.figure(figsize=[10,8])
plt.plot(data['Mes'], data['data science'], label='data science', color='black',linestyle='dashed', linewidth=4)
plt.plot(data['Mes'], data['machine learning'], label='machine learning')
plt.plot(data['Mes'], data['deep learning'], label='deep learning')
plt.title('Popularidad de Terminos Buscados por fecha')
plt.xlabel('Fecha')
plt.ylabel('Popularidad')
plt.grid(True)
plt.legend()
plt.savefig('grafico.pdf')
plt.show()

### Ploteando directamente un Dataframe

Dataframes tienen el metodo .plot() que plotea sus columnas con respecto a su indice

In [ ]:
data1 = data[['data science', 'machine learning', 'deep learning']]
data1.index = data['Mes']
data1.head()

In [ ]:
data1.plot(figsize=(10,8))
plt.title('Popularidad de Terminos Buscados por fecha')
plt.xlabel('Fecha')
plt.ylabel('Popularidad')
plt.grid(True)
plt.legend()
plt.show()

## Plots de Area

In [ ]:
data = pd.read_excel('ImmigrantsCanada.xlsx', sheet_name='Canada by Citizenship' )
data

In [ ]:
data.columns

In [ ]:
data.columns = list(map(str, data.columns))
data.columns

In [ ]:
data.set_index('Country', inplace=True)
data.head()

In [ ]:
data['Total'] = data.sum(axis=1)
data.head(3)

In [ ]:
years = list(map(str, range(1980, 2014)))
print(years)

In [ ]:
data.sort_values(by='Total', ascending=False, axis=0, inplace=True)
data_top5 = data[years].head(5)
data_top5

In [ ]:
data_top5 = data_top5.transpose()
data_top5.head()

In [ ]:
data_top5.plot( figsize= [12,8] )
plt.title('Evolucion de Inmigracion a Canada de los 5 paises mas aportan inmigrantes',fontdict={'fontsize':16})
plt.xlabel('Año')
plt.ylabel('Numero de Inmigrantes')
plt.grid(True)
plt.show()

In [ ]:
data_top5.plot(kind='area', stacked=True, figsize=(15, 8), alpha=0.2)
plt.title('Evolucion de Inmigracion a Canada de los 5 paises mas aportan inmigrantes')
plt.ylabel('Numero de Inmigrantes')
plt.xlabel('Año')
plt.grid(True)
plt.show()

## Plot de barras

* <b>kind=bar</b> a la funcion plot  genera un plot de barras verticales.  
* <b>kind=barh</b> a la funcion plot  genera un plot de barras horizontales.

### Barras verticales

In [ ]:
data

In [ ]:
data_haiti = data.loc['Haiti', years]
data_haiti.head()

In [ ]:
data_haiti.plot(kind='bar', figsize=(12, 6))
plt.xlabel('Año')
plt.ylabel('Numero de Inmigrantes')
plt.title('Inmigrants de Haiti hacia Canada entre 1980 a 2013')
plt.show()

In [ ]:
data_haiti_peru = data.loc[['Haiti', 'Peru'], years]
data_haiti_peru.head()

In [ ]:
data_haiti_peru.plot(kind='bar', figsize=(12, 6) )
plt.show()

In [ ]:
data_haiti_peru = data_haiti_peru.transpose()

In [ ]:
data_haiti_peru.plot( kind='bar', figsize=(12, 6) )
plt.xlabel('Año')
plt.ylabel('Numero de Inmigrantes')
plt.title('Inmigrants de Haiti y Peru hacia Canada entre 1980 a 2013')
plt.grid()
plt.show()

### Barras horizontales

In [ ]:
data.sort_values(by='Total', ascending=False, inplace=True)
data_top10 = data['Total'].head(10)
data_top10

In [ ]:
data_top10.plot(kind='barh', figsize=(12, 12), color='steelblue', )
plt.xlabel('Numero de Inmigrantes')
plt.title('10 Paises que mas contribuyen a la Inmigración a Canada entre 1980 - 2013')
plt.show()

In [ ]:
data_top10.sort_values( ascending=True, inplace=True)
data_top10.plot(kind='barh', figsize=(12, 12), color='steelblue', )
plt.xlabel('Numero de Inmigrantes')
plt.title('10 Paises que mas contribuyen a la Inmigración a Canada entre 1980 - 2013')
plt.show()

## Pie Plots

In [ ]:
data

In [ ]:
data_continents = data.groupby('Continent').sum()
data_continents

In [ ]:
data_continents['Total'].plot(kind='pie',
                              figsize=(5, 6),
                              autopct='%.1f%%',
                              startangle=90,
                              shadow=False )

plt.title('Inmigraciona a Canada por Continente entre 1980 - 2013')
plt.axis('equal')
plt.show()

## Scatter Plots

In [ ]:
data_insurance = pd.read_csv('Insurance.csv')
data_insurance

In [ ]:
data_insurance.isnull().values.any()

In [ ]:
data_insurance.info()

In [ ]:
data_insurance.plot(kind='scatter', x='age', y='charges', figsize=(10, 6), color='darkblue')

plt.title('Scatter plot: Prima de seguro de salud vs edad ')
plt.xlabel('Edad')
plt.ylabel('Prima de seguro')
plt.show()

## Histogramas

In [ ]:
data_insurance['age'].plot(kind='hist', bins=20, figsize=(8, 6))
plt.title('Histograma de la edad de los usuarios')
plt.ylabel('conteo')
plt.xlabel('edad')
plt.show()

In [ ]:
data_insurance['bmi'].plot(kind='hist', bins=50, figsize=(8, 6))
plt.title('Histograma del BMI')
plt.ylabel('conteo')
plt.xlabel('bmi')
plt.show()

## Plot de Densidad

In [ ]:
data_insurance['bmi'].plot(kind='density', figsize=(8,6))
plt.title('Plot de densidad del BMI')
plt.ylabel('densidad')
plt.xlabel('bmi')
plt.show()

## Plot de Matriz de Correlaciones

In [ ]:
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data_diabetes = pd.read_csv(filename, names=names)
data_diabetes.head()

In [ ]:
correlations = data_diabetes.corr( )
correlations

In [ ]:
correlations.style.background_gradient()